# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.author }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
remote_theme: yous/whiteglass

title: Jurgen Treep
author: Jurgen Treep
description: My little corner of the web where I write whatever comes to mind. It's often about technology but I also like to write about other things sometimes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jurgentreep.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: Europe/Amsterdam
exclude:
  - README.md

# Social media
twitter_username:
twitter_image:
facebook_app_id:
facebook_image:
google_analytics: UA-49010659-4
comments: true

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/